### ISSUE TITLE
Translations mistagged for several words

### ISSUE THREAD

**Issue by ChristianSi** [tatuylonen/wiktextract#112]
I noticed a problem with the parsing of translations in several words. For [grass](https://kaikki.org/dictionary/English/meaning/g/gr/grass.html), *all* translations seem to have the following properties:

    "lang": "Abenaki", "code": "abe", "sense": "ground cover plant"

Which is clearly wrong! The translations of other senses such as "lawn" and "marijuana" either seem to be missing from the dump, or they are mistagged.

With [red](https://kaikki.org/dictionary/English/meaning/r/re/red.html), the adjective is parsed correctly, but for the noun, all translations are tagged "Afrikaans".

And regarding [wolf](https://kaikki.org/dictionary/English/meaning/w/wo/wolf.html): for the noun, all translations are tagged "Abaza".

In all these cases, the extractor somehow seems to get stuck with the first translation and wrongly apply some of its properties to the other translations as well. I wouldn't be surprised if some other words have the same problem, but these are the three cases I noticed.

**Comment by ChristianSi** [comment]
Any news on this one?

@tatuylonen Did you already take a look?

**Comment by ChristianSi** [comment]
Ping?

I must admit this one worries me a bit. It's annoying that the translations of these three words are effectively lost, but it's disquieting that I don't know many many other words may be affected. Therefore I would be very happy if there was a chance of getting this fixed.

**Comment by tatuylonen** [comment]
Sorry I had missed this (I've been preoccupied by other stuff in the last few weeks but hoping to spend more time on wiktextract soon).  I'll try to look into this tomorrow.

**Comment by tatuylonen** [comment]
The entry for "grass" has syntax in the translations section that I've never seen before.  It begins:
====Translations====
{{trans-top|ground cover plant}}
{{#invoke:User:Erutuon/multitrans|expand|
&lt;nowik&gt;
* Abenaki: {{t|abe|mskiko}}
...

I think the &lt;nowiki&gt; tag is what is causing confusion here, and I'm probably handling it differently when it is used as a template argument like this and apparently handled specially by the template.  However, I'm still confused by the entry itself - why is the nowiki there in the first place?  And why do we have a mainstream word referencing a template in an individual user's namespace???

There are a few pages that reference the User:Erutuon/multitrans template (from a dump taken a few week ago), specifically: red, four, wolf, flower. I suspect these may have the same issue.

**Comment by kristian-clausal** [comment]
The list of affected articles (red, grass...) seems to be correct. It's an edit by user Erutuon, whose script this is, and looks like some sort of testing that was subsequently not removed. I've manually reverted the source of the articles to use {{multitrans|data= again the best I could, and left the edit-messages as "it was messing with a machine-reading project" in case someone's going to pick a fight over it.

There was an annoying surprise when I checked my edits later: there were some stray {{subst:#invoke:languages/templates|getByCode|aii|getCanonicalName}}-style language name templates that were automatically flattened/rendered somewhere in the editing process so that there's only "Northern Abkhazian" left in the source. Annoying, but probably not a problem.

**Comment by ChristianSi** [comment]
Thanks for finding this, @tatuylonen , and for removing the problem on Wiktionary's side, @kristian-clausal ! The three words I had found are among the five identified by @tatuylonen , so this should indeed completely solve the problem.

I suppose now we'll have to wait before a new dump with the fixed data was made and processed by wiktextract? That might take a while, I guess, but assuming that the problem should be fixed afterwards, it still seems a good solution.

**Comment by kristian-clausal** [comment]
Went through our dump of wiktionary edit-source to check for \<nowiki\> and #invoke stuff, and it is very rare. About twenty articles had #invoke, including the ones at issue here. \<nowiki\> is fifty times more common (1000~1200 articles), used mainly as a breaking non-space character and to do formatting that doesn't break because of apostrophes and \[\].

After some minor investigation to check if I find any blatantly broken stuff, it seems the stuff we've seen here (red, grass, wolf, four, flower) were just part of a perfect storm that combined \<nowiki\>, #invoke, and the only userspace script in #invoke that I could find to do _something_ that borked the parsing. The other uses of #invoke and what I saw of \<nowiki\> didn't cause issues for us.

**Comment by ChristianSi** [comment]
@kristian-clausal That sounds good!

Is there a timeline for when approximately a new dump with your fixes will appear on kaikki.org?

**Comment by kristian-clausal** [comment]
@ChristianSi Normally it would take maybe a few days, but there's been some issues recently. I don't think it can be done and uploaded piecemeal on kaikki.org one entry at a time. Instead, it's everything all at once, mainly because fixes on the wiktionary source side of things is usually not the focus, the concern is almost always the code-changes Tatu makes on this side that might affect everything.

**Comment by ChristianSi** [comment]
@kristian-clausal Bad news: someone has [reverted one of your edits](https://en.wiktionary.org/w/index.php?title=wolf&action=history) with the comment 'That template was the only thing preventing an "out of memory" errot'. I don' really get what's meant by that – I don't get an errors even on your version of the page.

However, I'm not sure whether this can be resolved peacefully, and an edit war wouldn't be good. I think I'll ask User:Erutuon directly about their script and why they need the <nowiki> tag there.

If that doesn't lead anywhere, it might be needed to add a workaround to the extractor code...

**Comment by ChristianSi** [comment]
I have added a comment to [User_talk:Erutuon](https://en.wiktionary.org/wiki/User_talk:Erutuon#Problem_with_your_%22multitrans%22).

**Comment by kristian-clausal** [comment]
@ChristianSi If that's the case, I'll leave my edits to the wind and let them be reverted as they are.

**Comment by Erutuon** [comment]
Hi, I came here from the discussion on [my talk page](https://en.wiktionary.org/wiki/User_talk:Erutuon#Problem_with_your_.22multitrans.22) mentioned above. The nowiki multitrans technique will probably remain on some pages, because it provides a very effective hack to reduce Lua memory usage, and I've given it a proper template `{{multitrans-nowiki}}` so it isn't a direct module invocation anymore.

The [revision](https://en.wiktionary.org/?oldid=66102544) where the *wolf* page was edited to use `{{multitrans}}` again has Lua memory errors at the bottom. Apparently the other former nowiki multitrans pages that now use `{{multitrans}}` are fine though, because they don't appear in the [Lua memory error category](https://en.wiktionary.org/wiki/Category:Pages_with_module_errors) right now.

I haven't looked at the translation extraction code in this repo, but what I do for the database for the [enwikt-translations](https://enwikt-translations.toolforge.org/) Toolforge site is get the value of the first parameter, get the contents of the nowiki tag, and process it like the contents of a normal translation section. (Source [here](https://git.sr.ht/~erutuon/enwiktionary-translations-db/tree/342dd1ad7e8c746ef57027b3fcf769aca101b2cf/item/src/visitor.rs#L185), though probably not very informative.) My translation database only looks at headers and translation templates. Not sure if this repo relies on language or script labels; there may be some in nowiki multitrans templates that contain an un-substed `{{subst:...}}`, until I fix the translation adder gadget.

**Comment by ChristianSi** [comment]
@Erutuon Thanks for the detailed explanation here and on your talk page! And I like the new syntax, it's much cleaner and more understandable.

@tatuylonen  @kristian-clausal So it seems the extractor will need a fix to handle this template. With the new syntax, it starts with

```
{{multitrans-nowiki|
<nowiki>
```

It should be possible to detect this and ignore the `<nowiki>` in this case? Right now it's used only on the [wolf](https://en.wiktionary.org/wiki/wolf#Translations) page, but there will certainly some more usages in the future.

**Comment by ChristianSi** [comment]
It seems that a new dump has made it to the site and I can confirm that *flower, four, grass*, and *red* are fine now – thanks to @kristian-clausal 's edits now doubt. The entry for *wolf* is still incomplete – in fact it seems that the translations are now missing altogether. I still hope that it'll be possible to add a workaround for this case, especially considering that this likely won't remain the only page where the `multitrans-nowiki` template will be used.

**Comment by ChristianSi** [comment]
Any news on this one? The translations for *wolf* are still missing.

**Comment by tatuylonen** [comment]
I think I just fixed this issue.  At least translations are now parsed for "wolf".  The main issue turned out to be that I replaced all sequences of whitespace (including newlines) by a single space inside &lt;nowiki&gt;...&lt;/nowiki&gt;.  This broke later processing with the multitrans-nowiki template.  The fix probably applies to all words using the multitrans-nowiki template.

The change should be reflected on https://kaikki.org within a couple of days.

**Comment by ChristianSi** [comment]
Sadly, the [translations of wolf](https://kaikki.org/dictionary/English/meaning/w/wo/wolf.html) are still broken on kaikki.org and in the dump, though "a couple of days" have surely passed. Maybe there is still a problem with the bugfix? Or when will the change actually make it to kaikki.org?

**Comment by ChristianSi** [comment]
Any news? The "wolf" entry is still broken.

**Comment by tatuylonen** [comment]
Interesting, it works in my development environment (using a several weeks old cache file) but not in production (which uses the latest dump).  Something has probably changed in Wiktionary during May that broke it again.  I'm currently running the extraction to update my development environment to the latest version and I'm planning to look at this again later today.

[We had problems getting the website update to go through between roughly May 2-17 and the site didn't update during that period]

**Comment by tatuylonen** [comment]
I just tested with the 20220520 dump in my dev environment and "wolf" translations seem to be parsed correctly.

Aha, turns out I had forgotten to commit my changes to Wikitextprocessor when I fixed the translations for "wolf" four weeks ago.  I just committed them.  The fix should now be reflected on https://kaikki.org tomorrow (by around noon Central European time).

**Comment by tatuylonen** [comment]
I seem to have broken it again when fixing test failure related to my nowiki changes interacting with preformatted text.  Looking into it...

**Comment by tatuylonen** [comment]
I finally fixed this again.  The problem was that my earlier fix broke handling multi-line <nowiki>...</nowiki> after a space, i.e., inside preformatted text, and my earlier fix broke tests related to that (and the construct has actually been used somewhere).
Anyway, now "wolf" translations should work.  The fix should be reflected on https://kaikki.org tomorrow.

**Comment by kristian-clausal** [comment]
The version on kaikki.org has updated, and the output is correct: wolf/English now has the correct language tags for each translation in translations. Closed as fixed.
