### ISSUE TITLE
Many English words lack translations in latest dump

### ISSUE THREAD

**Issue by ChristianSi** [tatuylonen/wiktextract#207]
In the latest batch, a pretty large number of English words seems to miss their translations (I don't know what else might be missing as well, since I only work with the translations. Here is a very incomplete list – "en" is the English word, "sense" the sense under which translations should be grouped. Usually I only list one sense in each case, but as far as I can tell, usually all senses for a word or a word/word class combination are missing; e.g. "water"/noun still has translations, but not "water"/verb.

en: Armenia
sense: ancient kingdom and country

en: China
sense: country in East Asia

en: dictionary
sense: publication that explains the meanings of an ordered list of words

en: discover
sense: find something for the first time

en: dry
sense: free from liquid or moisture

en: egg
sense: approximately spherical or ellipsoidal body produced by birds, insects, reptiles, and other animals, housing the embryo within a membrane or shell during its development

en: Estonia
sense: country

en: evening
sense: time of day between the approximate time of midwinter dusk and midnight

en: face
sense: front part of head

en: husband
sense: male partner in marriage

en: India
sense: the country

en: Israel
sense: the state

en: Japan
sense: a country in East Asia

en: Mars
sense: god of war
sense: planet

en: Portugal
sense: country

en: -stan
sense: used in actual place names

en: tongue
sense: organ

en: water
sense: to pour water into the soil surrounding (plants)

en: wolf
sense: animal

en: world
sense: human collective existence

en: zero
sense: cardinal number before 1, denoting nothing

In some cases, these word entries are tagged with "error-lua-exec" in kaikki; in other cases, the translations just seem to be missing without further comment.

There are certainly much more words affected; I only get notified of this in a small subset of cases. It would be great if this could be fixed soon, since the dump is unusable for me as long as it persists! Last week's dump already had a similar problem, but it seems to have gotten more severe, with more translations missing than before.

**Comment by kristian-clausal** [comment]
The last Wikipedia dump caused a lot of issue for us because it exposed a previously hidden Lua issue, there was a pinned thread. This seems to be part of that, although we got it most of it to work. In the meanwhile you have to use an old extraction from the previous dump. The data doesn't change that much, and we try to improve as we can, but if there's something that you can't use it's the same as if we didn't touch the code at all.

**Comment by kristian-clausal** [comment]
The culprit is most likely a newly created [Tibetan module](https://en.wiktionary.org/wiki/Module:Tibt-common), so it actually seems this isn't our fault, but it might be that the last dump just got a faulty module in it.

**Comment by kristian-clausal** [comment]
Tatu took a look at this, and after bughunting for a long time he found a bug with module loading that should now be fixed, which snagged on one edge case that was then found in the new Tibetan modules. Kaikki should be fine in a day or two.

**Comment by kristian-clausal** [comment]
We're running into all sorts of problems, so this might take a while...

**Comment by kristian-clausal** [comment]
Kaikki.org has finally revived, and it seems this issue has been fixed, closing this thread.

**Comment by ChristianSi** [comment]
Sadly it doesn't seem this has been fixed altogether. Many words have re-appared/re-found their translations, but there are still some where the translations (and possibly other details) are missing. These include:

* -stan (suffix)
* evening
* Portugal
* husband (noun)

The word "discover" seems to be missing altogether.

Maybe it's just a question of the website and the dump not yet being updated from the latest code? If not, could you please re-open and investigate this?

**Comment by kristian-clausal** [comment]
I think I have located the problem with "evening" (which is the only one I've looked at), there's something wrong with the parsing of levels (====Synonym====) with it. This might take a while.

**Comment by kristian-clausal** [comment]
Fixed in wikitextprocessor cba632c2bbb8f4ca2b88708aca689985b225e1dd

When I fixed an earlier issue with single quotes inside html tags, I used a pretty naive regex searching for HTML tags. After finding it, was pretty simple to fix it using ALLOWED_HTML_TAGS, except for some unfathomable reason I got a lot of naked "div" strings in the output! Why did this regex strip away the `</>` parts of the the `</div>`?? Well, after a while I found the culprit in re.split's capture groups: it doesn't just return the outermost capture groups, it will *also* return all inner capture groups, creating duplicate ghosts of the tag-names. Well, should work now.

**Comment by kristian-clausal** [comment]
Yeah, I finally got kaikki to update correctly and seems this is corrected there, too, now.

**Comment by ChristianSi** [comment]
Yeah, that looks really good now! The only word that's still missing is **Portugal**. Indeed, as far as I can tell, that word doesn't exist in the kaikki dump at all. So I guess there must still be some kind of crash when it's processed?
