### ISSUE TITLE
Gender markers in translations

### ISSUE THREAD

**Issue by ChristianSi** [tatuylonen/wiktextract#63]
In today's dump, the romanization of Russian translations in the English dump has totally broken down. In nearly all cases, the Latin form is listed in parentheses after the Cyrillic word in the "word" field, while the "roman" field is missing.

For my this is a showstopper, I cannot use the dump without these romanizations and have to revert to an older version. So I hope this will be fixed quickly!

**Comment by ChristianSi** [comment]
The original issue has fixed itself in the latest dump. However, now the gender markers (m/fn) are treated as part of the word. This seems to affect translations into all or at least many languages that have genders. Some examples:

* ru: "отклоне́ние n"
* es: "abolicionismo m"
* fr: "abolitionnisme m"
* it: "abolizionismo m"
* pt: "abolicionismo m"
* ur: "ابراہیم‎ m"
* de: "Bäckerdutzend n"
* fr: "foi f", "croyance f"

Again this makes the dump unusable for me, so I hope for a quick solution

**Comment by tatuylonen** [comment]
This should now be fixed (also on the web site).  It was broken by a recent change in classify_desc() in form_descriptions.py.

I need to implement more tests to make bugs like this less likely...

**Comment by tatuylonen** [comment]
I just implemented tests for classify_desc().  This should make this particular issue much less likely in the future.

**Comment by ChristianSi** [comment]
That's good to hear!

The latest dump is still from last night, so I guess it'll be a few hours until this show up on the website?

**Comment by tatuylonen** [comment]
I just started a website regeneration run, but the fixes to the gender markers was already fixed last night (I fixed the underlying problem yesterday before seeing the bug report).

The extraction/website regeneration run now also runs tests before starting the extraction and aborts if any test fails.  I'll be adding more tests to reduce the risk of major problems; however, some parts of Wiktextract are quite difficult/slow to test without the full run or at least creating a cache file, as a lot of operations depend on having access to all the templates defined in the dump.  Thus at least for now the tests will mostly be on some of the lower-level functions.

**Comment by tatuylonen** [comment]
Sorry, I just realized you actually reported two different problems.  So the romanization issue should be fixed.  Regarding the gender marker issue, could you please clarify which word these examples were from?  (I don't issue in the current version on the website though, looking at a few random words.)

**Comment by ChristianSi** [comment]
Oh, sorry for the confusion. I'd change the issue because, when I re-downloaded the dump today, the romanization was fixed and the gender marker problem had appeared. That's still the case – the dump is from 2021-07-10 01:19:22 (don't ask my about the timezone, please). As far as I can tell, nearly all words with translations into languages such as Spanish, French, German, Russian etc. have this issue, but one word where I see it in many translations is "abolitionism".

**Comment by tatuylonen** [comment]
It is still not fixed.  I'm looking into it now.

**Comment by tatuylonen** [comment]
I found the problem.  I had carelessly added a .strip() call in parse_head_final_tags() and it resulted in the gender tags
in translations and linkages to be ignored if the last character of the page title was the same as the gender tag.

I just restarted generating the web site.  The data should update within five hours.

**Comment by ChristianSi** [comment]
This looks pretty good now! Most of the spurious gender markers are now gone, so the dump is usable again. Thanks a lot!

However, I still noticed a few spurious gender markers which weren't there in the past. This include:

German translation:

* assessment (sense: appraisal): "Schätzung f"
* Botswanan (person from Botswana): "Botswanerin f"
* collier (person) "Bergmann m"

Portuguese translation:

* breakfast (first meal of the day): "desjejum f" (the word "(Angola) " in the next translation also doesn't belong there)

Spanish translation:

* brewing (production of alcoholic beverages): "elaboración de cerveza f"
* elegy (mournful or plaintive poem or song): "elegía f"
* zero (nothing, or none): "nula f"

French translation:

* connection (point at which two or more things are joined): "liaison f"
* flaw (crack or breach): "fissure f"

Other words are affected as well; as usual, these are just examples.

**Comment by ChristianSi** [comment]
Since this issue has somehow come to involve two problems, I would also like to report that, while most Russian transliterations are fine again, a few are still missing. These include:

* dial (disk with finger holes on a telephone): transliteration of "набо́рный диск"

Some Japanese transliterations have got lost. Affected words include:

* chocolate chip (small piece of chocolate)
* colliery (underground coal mine)
* Congo (river)

For "conjugation" (fusion of organisms), one Japanese translation is "結合
(けつごう, ketsugō)", mixing both spellings and the transliteration.

Some Hindi transliterations were also lost, e.g. for:

* close (move (a door))
* Hindu Kush (mountain range): transliteration of "हिन्दूकुश"

And Arabic:

* documentary (documentary film)
* ectothermic (of or relating to ectotherm; having an unregulated body
  temperature)

All these examples refer to transliterations that were correctly detected until a few days ago.

**Comment by tatuylonen** [comment]
Your first list (f or m in some translation) was all due to coding errors in Wiktionary:
- comma at end of translations list (such commas are now automatically removed)
- two commas between translations (the extra comma is now automatically removed)
- missing space between translations (this is tricker, and I did not yet implement a generic fix; I think I fixed something else by tightening how I split the translations; I'll look into this in more detail tomorrow)

I fixed all these cases in Wiktionary, but as you note, they are probably only the tip of the iceberg and I'll probably need to implement a more generic solution for the missing space case too.

Your second batch was due to romanization being classified as english.  I fixed these by the following changes to the classification code:
- never consider something "english" if it is not 7-bit ascii
- don't consider second words of taxonomic species names as English now that english recognition has been relaxed

I also added a few more test cases that should catch these if they ever resurface.

The "conjugation" one was due to an extra comma at the end (I also fixed it in Wiktionary).

I started a database update, but I'm sure there will be more cases of missing space in Wiktionary, and these will result in further m/f remaining cases.  I'll look into translations with a remaining comma in more detail tomorrow (starting by extracting all such cases from the extracted json file).

**Comment by tatuylonen** [comment]
There are a couple of thousand cases that are still not handled that I can find.  I will clearly need to re-relax the rules for splitting translations and deal with the problem cases somehow separately.  It may take a few days for this to stabilize.

**Comment by ChristianSi** [comment]
I'm very much impressed by how patently you massage the unruly Wiktionary data into a machine-readable form!

Personally I would consider it acceptable to close this issue now, since all the problems I had noticed are fixed and the number of translations that still have issues seems to be quite limited. But since you've indicated that you're still working on this, I'll leave it to you to close this issue once you're satisfied with the results.

**Comment by yolpsoftware** [comment]
Indeed, Tatu, I cannot stress enough how much your work here is appreciated! I always thought Wiktionary is the one Wiki that is too chaotic to be parsable, and I'm not the only one to have thought that.

**Comment by ChristianSi** [comment]
You may be aware of it already, but in the latest dump, spurious gender markers are back, this time in the form "x or" added at the end of translations. Most common is "m or", occurring in thousands of words. One example:

* academic (n) – fr: "universitaire m or"

But there are also others, e.g.:

* hentai (n) – de: "Hentai m or f or"
* feminazi (n) – es: "feminazi f or"
* abstract (v) – ru: "абстраги́ровать impf or"
* water buffalo (n) – sw: "nyati 9/10 or"

**Comment by tatuylonen** [comment]
I fixed some issues in linkage parsing on Saturday that likely caused this (it calls the same function to parse tags from the end of the form).  The old method was more general but didn't always work and sometimes ate parts of the actual word form.  Some of the patterns are clearly missing from the new method but should be easy to add.  I'm hoping to fix this today.

I implemented the first 130 tests for linkage parsing over the weekend.  I'm planning to implement tests for translation parsing later this week.

**Comment by tatuylonen** [comment]
I found over 19000 instances of translations now ending in " or" (earlier it was a few dozen).  The vast majority of these are errors.  I've implemented fixes for most of them (probably 99%), but there are probably some that I missed on this round.  I'll check again tomorrow to fix the remaining ones.  A few are valid translations ending in "or" (e.g., Greek translation of "logical or") and a few are due to errors in Wiktionary (e.g., "m or ma" or "u or u" suffixes for certain Swahili translations that I believe to be typos in Wiktionary).

The website update is running; it should complete in about five hours (unless some error occurs).

**Comment by ChristianSi** [comment]
Looks much better now after the latest update! But I still see more than a hundred translations ending in stuff such as "f or", "f sg or", "m or", "n or", "pl or", "11 or" that almost certainly should not be there. German, Swahili, Russian, French and Italian seem particularly affected. Perfection is certainly unachievable, but I hope you'll be able to fix some more of them.

**Comment by tatuylonen** [comment]
I found about 900 of them today.  I again fixed most of the cases, but a some probably remain for tomorrow.  There is now also a debug message about them plus the diagnostic page on the web page has the errors structured better so it will hopefully make debugging these much easier as well.  And current tests would have detected issue before it ever got out.  (Dedicated tests for translation extraction are still mostly missing though.)

**Comment by tatuylonen** [comment]
I found 277 today.  I again fixed a lot of cases and will check again tomorrow.  An increasing fraction of them look suspicious in Wiktionary, but I don't know the various languages well enough to fix them there.  I'm adding recognition of even the weirder combinations but with a debug message so many of the questionable ones can be found.  There are also ones that can be found by inspecting the data; for example I've seen several references to "c" (for common gender as in Swedish, Norwegian, Danish etc) in Spanish, but I'm not aware of Spanish having such gender.

**Comment by ChristianSi** [comment]
This looks really good now! I'm closing this, as only very few cases remain now.

For completeness's sake, here are the words where I still spot problems – don't know whether it's due to input errors or some very special cases (some of them have two *or*s in a row):

* anadromous – ar: نَهْرِيَّةُ السَّرْءِ‎ m pl or
* form (v) – ru: сформировал m or
* Sindhi – es: sindí pl or
* striking – ar: لافِتَةٌ لِلنَّظَرِ‎ m pl or
* youth – pt: jovens m or
