### ISSUE TITLE
Canonical form of many Russian words is set to "f" or "m" or "n"

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#64]
I think this affects roughly 15.000 words or so. 

I don't know what else I should to add to the issue, other than expressing my gratitude for this great source of data. 👍

**Comment by tatuylonen** [comment]
Thanks for reporting this!  I implemented a fix, but it really needs more testing.  I started regenerating the site and it the results of the fix should be visible tomorrow (about five hours from now), unless something goes wrong with the run (with is possible due to the limited testing).  The fix probably covers the vast majority of the cases, but I don't know if it covers them all.

**Comment by tatuylonen** [comment]
The update failed last night (two separate places where the code crashed on some places).  I fixed those and restarted; it should now update in about five hours.

**Comment by tatuylonen** [comment]
I fixed one more crash and restarted the update run, so hopefully it should complete about five hours from now.

**Comment by Vuizur** [comment]
Hmm, the issue still seems to persist on the 2021-07-22 JSON data.

**Comment by tatuylonen** [comment]
I fixed an issue with my previous fix that should fix many of these.  Some will probably be due to other causes and I'll analyze them in more detail tomorrow or Monday once I get the once covered by the current fix out of the way.

**Comment by tatuylonen** [comment]
This is still work in progress.  I'm checking the remaining ones from each new extraction and trying to fix (at least some of) the remaining issues on each round.

**Comment by tatuylonen** [comment]
As far as I know these should now all be fixed.  Please let me know if you know of any that remain.  Otherwise I'll close this issue in about a week.
